name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

schedules:
  - cron: "0 0 * * *"
    displayName: Daily PR cleanup
    branches:
      include:
        - master
    always: true

jobs:
  - job: build
    displayName: Build & Test
    timeoutInMinutes: 30
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - checkout: self

      - task: DownloadSecureFile@1
        name: aws_config
        inputs:
          secureFile: ptl_aws_config

      - bash: |
          mkdir -p ~/.aws
          mv $(aws_config.secureFilePath) ~/.aws/config
          chmod 400 ~/.aws/config
        displayName: "Get AWS config"

      - template: build-prereqs.yml
        parameters:
          utils_dir: './'

      - bash: |
          make -C ansible remove-old-ecs-pr-deploys
        displayName: "cleanup older pr deploys"
