- name: set image_name fact
  set_fact:
    image_name: "{{ ecr_registry }}/{{ service_id }}_{{ item }}:{{ build_label }}"

- name: find most recent tag
  command: >
    {{ aws_cmd }} ecr describe-images --repository-name {{ service_id }}_{{ item }} --filter tagStatus=TAGGED --no-paginate
    --query 'imageDetails[0].imageTags[0]' --output text
  register: describe_images
  changed_when: no

- name: pull latest if exists - to ensure cache  {{ item }}
  ansible.builtin.command:
    cmd: "docker pull {{ ecr_registry }}/{{ service_id }}_{{ item }}:{{ describe_images.stdout }}"
  when: describe_images.stdout != 'None'
  ignore_errors: true
  no_log: true

- name: build ecr image {{ item }}
  ansible.builtin.command:
    cmd: >
      docker build
      -t {{ image_name }}
      -f {{ base_dir }}/{{ images_map[item].dockerfile }}
      {{ base_dir }}/{{ images_map[item].path }}
      --network host --pull
  register: build_result
  ignore_errors: false

- name: push ecr image {{ item }}
  ansible.builtin.command:
    cmd: "docker push {{ image_name }}"
  when: build_result.rc == 0

- name: List contents of playbook_dir
  ansible.builtin.command: >
    ls -al {{ playbook_dir }}
  register: ls_playbook

- name: Show playbook_dir contents
  debug:
    var: ls_playbook.stdout

- name: Get existing lifecycle policy JSON for {{ service_id }}_{{ item }}
  ansible.builtin.command: >
    {{ aws_cmd }} ecr get-lifecycle-policy
    --repository-name {{ service_id }}_{{ item }}
    --query 'lifecyclePolicyText'
    --output text
  register: existing_policy_raw
  failed_when: false
  changed_when: false

- name: Parse existing lifecycle policy JSON if present
  set_fact:
    existing_policy_json: "{{ existing_policy_raw.stdout | from_json }}"
  when:
    - existing_policy_raw.stdout is defined
    - existing_policy_raw.stdout != ""
    - existing_policy_raw.stdout != "None"
    - existing_policy_raw.stdout != "null"

- name: Ensure existing_policy_json always exists
  set_fact:
    existing_policy_json: {}
  when: existing_policy_json is not defined

- name: Read lifecycle policy from the shared file
  ansible.builtin.slurp:
    src: "{{ playbook_dir }}/../ecr-lifecycle/ecr_lifecycle.json"
  register: desired_policy_raw

- name: Decode lifecycle policy file
  set_fact:
    desired_policy_json: "{{ desired_policy_raw.content | b64decode | from_json }}"

- name: Apply lifecycle policy to ecr {{ service_id }}_{{ item }} if different
  ansible.builtin.command: >
    {{ aws_cmd }} ecr put-lifecycle-policy
    --repository-name {{ service_id }}_{{ item }}
    --lifecycle-policy-text file://{{ playbook_dir }}/../ecr-lifecycle/ecr_lifecycle.json
  when:
    - existing_policy_json != desired_policy_json
