- name: set image_name fact
  set_fact:
    new_policy

- name: get current repository policy
  command: "{{ aws_cmd }} ecr get-repository-policy --repository-name {{ item }} --query policyText --output text"
  register: get_current_policy
  failed_when: get_current_policy.rc !=0 and 'RepositoryPolicyNotFoundException' not in get_current_policy.stderr
  changed_when: no

- name: check if policy needs updating
  set_fact:
    do_update: "{{ get_current_policy.rc == 255 or (get_current_policy.stdout | from_json) != cross_account_policy }}"

- name: set cross accout policy
  command: >-
    {{ aws_cmd }} ecr set-repository-policy --repository-name {{ item }}
    --policy-text '{{ cross_account_policy | to_json  }}'
  when: do_update
