- name: parse_created_at
  set_fact:
    should_remove: >-
      {{
        (
          (
            (ansible_date_time.iso8601[:18] | to_datetime('%Y-%m-%dT%H:%M:%S')) -
            (item.created[:18] | to_datetime('%Y-%m-%dT%H:%M:%S'))
          ).total_seconds() / 3600
        ) >= (retain_hours | int)
      }}
    age_hours: >-
      {{
        (
          (
            (ansible_date_time.iso8601[:18] | to_datetime('%Y-%m-%dT%H:%M:%S')) -
            (item.created[:18] | to_datetime('%Y-%m-%dT%H:%M:%S'))
          ).total_seconds() / 3600
        )
      }}

- debug:
    msg:
      - "name, {{ item.name }}"
      - "created at, {{ item.created }}"
      - "current_date, {{ ansible_date_time.iso8601 }}"
      - "age_hours, {{ age_hours }}"
      - "should remove,  {{ should_remove }}"

- name: "removing spec {{ item.name }}"
  uri:
    url: "{{ specs_resource_uri }}/{{ item.id }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ APIGEE_ACCESS_TOKEN }}"
  when: should_remove
  changed_when: yes