- name: extract vars
  set_fact:
    spec_time_created: "{{ item.created }}"

- debug:
    msg: "{{ spec_time_created }}" 

- name: parse_created_at
  set_fact:
    should_remove: >-
      {{
        (
          (
            (ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ')) -
            (spec_time_created | to_datetime('%Y-%m-%dT%H:%M:%SZ'))
          ).total_seconds() / 3600
        ) >= (retain_hours | int)
      }}
    age_hours: >-
      {{
        (
          (
            (ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ')) -
            (spec_time_created | to_datetime('%Y-%m-%dT%H:%M:%SZ'))
          ).total_seconds() / 3600
        )
      }}

- debug: 
    msg:
      - "name, {{ item.name }}"
      - "created at, {{ item.created }}"
      - "current_date, {{ ansible_date_time.iso8601 }}"
      - "age_hours, {{ age_hours }}"
      - "should remove,  {{ should_remove }}"
