- name: parse_created_at
  set_fact:
    should_remove: >-
      {{
        (
          (
            (ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ')) -
            (item.created | to_datetime('%Y-%m-%dT%H:%M:%S.%fZ'))
          ).total_seconds() / 3600
        ) >= (retain_hours | int)
      }}
    age_hours: >-
      {{
        (
          (
            (ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ')) -
            (item.created | to_datetime('%Y-%m-%dT%H:%M:%S.%fZ'))
          ).total_seconds() / 3600
        )
      }}

- debug: 
    msg:
      - "name, {{ item.name }}"
      - "created at, {{ item.created }}"
      - "current_date, {{ ansible_date_time.iso8601 }}"
      - "age_hours, {{ age_hours }}"
      - "should remove,  {{ should_remove }}"

- debug:
    msg: "Removing {{ item.name }}"
  when: should_remove

- name: remove pr spec
  uri:
    url: "{{ specs_resource_uri }}/{{ item.id }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ APIGEE_ACCESS_TOKEN }}"