
parameters:
  - name: 'env_vars_dir'
    type: string
    default: './'
  - name: 'utils_dir'
    type: string
    default: 'utils'

steps:

  - bash: |
      set -e
      source "{{ parameters.env_vars_dir }}/.build_env_vars"

      ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
      ASSUME_ROLE="deploy-${APIGEE_ENVIRONMENT}-${service_id}"

      cp ~/.aws/config.default ~/.aws/config
      tmp_file="$(Agent.TempDirectory)/.aws.tmp.creds.json"
      aws sts assume-role --role-arn "arn:aws:iam::${ACCOUNT_ID}:role/${ASSUME_ROLE}" --role-session-name build-assume-role > ${tmp_file}

      echo "aws_access_key_id = $(jq -r .Credentials.AccessKeyId ${tmp_file})" >> ~/.aws/config
      echo "aws_secret_access_key = $(jq -r .Credentials.SecretAccessKey ${tmp_file})" >> ~/.aws/config
      echo "aws_session_token = $(jq -r .Credentials.SessionToken ${tmp_file})" >> ~/.aws/config

      rm ${tmp_file}

    displayName: "assume deployment role"

