name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

schedules:
  - cron: "0 2 * * *"
    displayName: Daily PR cleanup
    branches:
      include:
        - master
    always: true

jobs:
  - job: build
    displayName: Cleanup ECS PR Proxies
    timeoutInMinutes: 240
    pool:
      name: 'AWS-ECS'
    steps:
      - checkout: self

      - bash: |
          set -e
          mkdir -p ~/.aws
          rm -f ~/.aws/config || true
          echo '[default]' > ~/.aws/config
          echo 'region = eu-west-2' >> ~/.aws/config
          echo 'output = json' >> ~/.aws/config
          chmod 600 ~/.aws/config
          cp ~/.aws/config ~/.aws/config.default
        displayName: clean aws config

      - bash: |
          set -e
          ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
          ASSUME_ROLE="auto-ops"

          cp ~/.aws/config.default ~/.aws/config
          tmp_file="$(Agent.TempDirectory)/.aws.tmp.creds.json"
          aws sts assume-role --role-arn "arn:aws:iam::${ACCOUNT_ID}:role/${ASSUME_ROLE}" --role-session-name build-assume-role > ${tmp_file}

          echo "aws_access_key_id = $(jq -r .Credentials.AccessKeyId ${tmp_file})" >> ~/.aws/config
          echo "aws_secret_access_key = $(jq -r .Credentials.SecretAccessKey ${tmp_file})" >> ~/.aws/config
          echo "aws_session_token = $(jq -r .Credentials.SessionToken ${tmp_file})" >> ~/.aws/config

      - template: build-prereqs.yml
        parameters:
          utils_dir: './'

      - bash: |
          make -C ansible remove-old-ecs-pr-deploys
        displayName: "cleanup older pr deploys"
