name: "$(SourceBranchName)+$(BuildID)"

trigger: none

pr: none

parameters:
  - name: service_name
    displayName: Name of service to be removed
    type: string
    default: ""

  - name: service_name_short
    displayName: Short name of service to be removed
    type: string
    default: ""

  - name: has_ecs_backend
    displayName: Target service has ecs backend
    type: boolean
    default: False

  - name: environment
    displayName: Name of target environment
    type: string
    default: ""

  - name: remove_ecr_build_role
    displayName: Tick to include the removal of the ECR build role 
    type: boolean
    default: False
  
  - name: force_remove_from_apps
    displayName: Tick to force remove specifed product from subscribed apps
    type: boolean
    default: False


stages:
  - ${{ if in(parameters.environment, 'internal-qa', 'ref', 'internal-qa-sandbox', 'internal-dev-sandbox', 'internal-dev') }}:
      - template: ./components/cleanup-proxy-choose-approval.yml
        parameters:
          apigee_org: nonprod         
          service_name: ${{ parameters.service_name }}
          service_name_short: ${{ parameters.service_name_short }}
          has_ecs_backend: ${{ parameters.has_ecs_backend }}
          APIGEE_ENVIRONMENT: ${{ parameters.environment }}
          remove_ecr_build_role: ${{ parameters.remove_ecr_build_role }}
          force_remove_from_apps: ${{ parameters.force_remove_from_apps }}

  - ${{ if in(parameters.environment, 'dev', 'int', 'sandbox', 'prod') }}:
      - template: ./components/cleanup-proxy-choose-approval.yml
        parameters:
          apigee_org: prod
          service_name: ${{ parameters.service_name }}
          service_name_short: ${{ parameters.service_name_short }}
          has_ecs_backend: ${{ parameters.has_ecs_backend }}
          APIGEE_ENVIRONMENT: ${{ parameters.environment }}
          remove_ecr_build_role: ${{ parameters.remove_ecr_build_role }}
          force_remove_from_apps: ${{ parameters.force_remove_from_apps }}
