name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

parameters:
  - name: org
    displayName: Organisation of target proxy
    type: string
    default: nonprod
    values:
    - nonprod
    - prod

  - name: service_name
    displayName: Name of service to be removed
    type: string
    default: ""

  - name: service_name_short
    displayName: Short name of service to be removed
    type: string
    default: ""

  - name: has_ecs_backend
    displayName: Target service has ecs backend
    type: boolean

  - name: environment
    displayName: Name of target environment
    type: string
    default: ""


jobs:
  - job: build
    displayName: Cleanup Named Proxy
    timeoutInMinutes: 240
    pool:
      name: 'AWS-ECS'

    workspace:
      clean: all

    steps:

      - checkout: self

      - bash: |
          instance_id="$(curl -s http://169.254.169.254/latest/meta-data/instance-id)"
          echo instance-id: "${instance_id}"
          echo connect to: https://eu-west-2.console.aws.amazon.com/systems-manager/session-manager/${instance_id}
          echo sudo su - ubuntu
          or
          echo ssh ubuntu@${instance_id}
          echo working directory: $(System.DefaultWorkingDirectory)
        displayName: print aws info

      - template: ./components/aws-assume-role.yml
        parameters:
          role: "auto-ops"
          profile: "apm_ptl"

      - bash: |
          tfenv use 0.14.6
        displayName: setup terraform

      - bash: |
          make install
        displayName: install dependencies

      - bash: |
          export SERVICE_NAME="$(service_name)"
          export SERVICE_NAME_SHORT="$(service_name_short)"
          export has_ecs_backend="$(has_ecs_backend)"
          export APIGEE_ENVIRONMENT="$(environment)"
          export APIGEE_ORGANIZATION="nhsd-$org"
          export APIGEE_ACCESS_TOKEN="$(secret.AccessToken)"
          export retain_hours=72
          ANSIBLE_FORCE_COLOR=yes make -C ansible remove-target-proxy
        displayName: "cleanup target portal apis"
