name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

parameters:
  - name: org
    displayName: Organisation of target proxy
    type: string
    default: nonprod
    values:
    - nonprod
    - prod

  - name: service_name
    displayName: Name of service to be removed
    type: string
    default: ""

  - name: service_name_short
    displayName: Short name of service to be removed
    type: string
    default: ""

  - name: has_ecs_backend
    displayName: Target service has ecs backend
    type: boolean

  - name: environment
    displayName: Name of target environment
    type: string
    default: ""


jobs:
  - job: build
    displayName: Cleanup Named Proxy
    timeoutInMinutes: 240
    pool:
      name: 'AWS-ECS'

    workspace:
      clean: all

    steps:

      - checkout: self

      - bash: |
          instance_id="$(curl -s http://169.254.169.254/latest/meta-data/instance-id)"
          echo instance-id: "${instance_id}"
          echo connect to: https://eu-west-2.console.aws.amazon.com/systems-manager/session-manager/${instance_id}
          echo sudo su - ubuntu
          or
          echo ssh ubuntu@${instance_id}
          echo working directory: $(System.DefaultWorkingDirectory)
        displayName: print aws info

      - template: ./components/aws-assume-role.yml
        parameters:
          role: "auto-ops"
          profile: "apm_ptl"

      - bash: |
          tfenv use 0.14.6
        displayName: setup terraform

      - bash: |
          make install
        displayName: install dependencies

      - bash: |
          export SERVICE_NAME="$(service_name)"
          export SERVICE_NAME_SHORT="$(service_name_short)"
          export has_ecs_backend="$(has_ecs_backend)"
          export APIGEE_ENVIRONMENT="$(environment)"
          export APIGEE_ORGANIZATION="nhsd-$org"
          export APIGEE_ACCESS_TOKEN="$(secret.AccessToken)"
          export retain_hours=72
          ANSIBLE_FORCE_COLOR=yes make -C ansible remove-target-portal-apis
        displayName: "cleanup target portal apis"

      - bash: |
          export SERVICE_NAME="$(service_name)"
          export SERVICE_NAME_SHORT="$(service_name_short)"
          export has_ecs_backend="$(has_ecs_backend)"
          export APIGEE_ENVIRONMENT="$(environment)"
          export APIGEE_ORGANIZATION="nhsd-$org"
          export APIGEE_ACCESS_TOKEN="$(secret.AccessToken)"
          export retain_hours=72
          ANSIBLE_FORCE_COLOR=yes make -C ansible remove-target-specs
        displayName: "cleanup target specs"

      - bash: |
          export SERVICE_NAME="$(service_name)"
          export SERVICE_NAME_SHORT="$(service_name_short)"
          export has_ecs_backend="$(has_ecs_backend)"
          export APIGEE_ENVIRONMENT="$(environment)"
          export APIGEE_ORGANIZATION="nhsd-$org"
          export APIGEE_ACCESS_TOKEN="$(secret.AccessToken)"
          export retain_hours=72
          ANSIBLE_FORCE_COLOR=yes make -C ansible remove-target-products
        displayName: "cleanup target products"

      - bash: |
          export SERVICE_NAME="$(service_name)"
          export SERVICE_NAME_SHORT="$(service_name_short)"
          export has_ecs_backend="$(has_ecs_backend)"
          export APIGEE_ENVIRONMENT="$(environment)"
          export APIGEE_ORGANIZATION="nhsd-$org"
          export APIGEE_ACCESS_TOKEN="$(secret.AccessToken)"
          export retain_hours=72
          ANSIBLE_FORCE_COLOR=yes make -C ansible remove-target-proxies
        displayName: "cleanup target proxies"

## TODO
# Change each step to not pr - DONE
# Create each step in makefile - DONE
# Create each playbook - DONE
# Create each role - DONE
# Edit each role to fit the new purpose
#    -portal-apis
#    -products
#    -proxies
#    -specs
#
## Things to check
# Check the steps are appropriate/accurate
# Check to see if APIGEE_ORGANIZATION will work with "nhsd-$org" (changed from coded nonprod)
# Check to see if retain_hours will still be needed (if we end up removing all commented bits - it will not be needed)
# Left out remove-old-auto-products and remove-old-auto-apps for now - was this correct? (auto-apps reffed in ACs)
# The matching of the service name (roles/tasks/main.yml) -- will this match exactly? will need to add a -* ?
# Similarly ^ remove_target_products used 'proper' regex (l25 l37) -- this will need to map/filter agaisnt SERVICE_NAME and SERVICE_NAME_SHORT idk how to do this.
# Extra similarly to ^ in remove_target_proxies regex again (l12 l24) -- same as ^ 
#
## Acceptance Criteria
#    Create a pipeline to clean up a specified proxy
#    Should include multiple params which could include
#        service name
#        service short name
#        has_ecs_backend
#        environment
#    Should have 'prod approval' on prod
#    If removing from subscriped apps should also require approval
#    Should be used to clean up the 'geneterated template api'
#    Create KOP on how to use
