name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

schedules:
  - cron: "0 2 * * *"
    displayName: Daily PR cleanup
    branches:
      include:
        - master
    always: true

jobs:
  - job: build
    displayName: Cleanup ECS PR Proxies
    timeoutInMinutes: 240
    pool:
      name: 'AWS-ECS'
    steps:
      - checkout: self

      -  template: ./components/aws-assume-role.yml
         parameters:
           role: "auto-ops"
           profile: "apm_ptl"

      - template: build-prereqs.yml
        parameters:
          utils_dir: './'

      - bash: |
          # temp this is till we can update to terraform 0.13.0 (which respects the profile setting over metadata)
          export AWS_ACCESS_KEY_ID="$(grep 'aws_access_key_id = ' ~/.aws/config | cut -d ' ' -f3)"
          export AWS_SECRET_ACCESS_KEY="$(grep 'aws_secret_access_key = ' ~/.aws/config | cut -d ' ' -f3)"
          export AWS_SESSION_TOKEN="$(grep 'aws_session_token = ' ~/.aws/config | cut -d ' ' -f3)"
          export retain_hours=72
          make -C ansible remove-old-ecs-pr-deploys
        displayName: "cleanup older pr deploys"
