name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

schedules:
  - cron: "0 2 * * *"
    displayName: Daily PR cleanup
    branches:
      include:
        - master
    always: true

jobs:
  - job: build
    displayName: Cleanup PR specs
    timeoutInMinutes: 240
    pool:
      vmImage: "ubuntu-20.04"
    steps:
      - checkout: self

      - task: DownloadSecureFile@1
        name: aws_config
        inputs:
          secureFile: ptl_aws_config

      - template: build-prereqs.yml
        parameters:
          utils_dir: "./"

      - template: "../components/set-facts.yml"
        parameters:
          service_name: ${{ parameters.service_name }}
          secret_ids:
            - ptl/azure-devops/apigee-nonprod/APIGEE_OTP_KEY
            - ptl/azure-devops/apigee-nonprod/APIGEE_PASSWORD
          config_ids:
            - /ptl/azure-devops/apigee-nonprod/APIGEE_USERNAME
            - /ptl/azure-devops/GITHUB_USER

      - bash: |
          make -C ansible remove-old-pr-portal-apis
        displayName: "cleanup old pr portal apis"

      - bash: |
          make -C ansible remove-old-pr-specs
        displayName: "cleanup old pr specs"
