name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

schedules:
  - cron: "0 2 * * *"
    displayName: Daily PR cleanup
    branches:
      include:
        - master
    always: true

jobs:
  - job: build
    displayName: Cleanup PR specs
    timeoutInMinutes: 240
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - checkout: self

  # TODO: Not implemented