apigee_management_api_uri: "https://api.enterprise.apigee.com/v1"
organization_api_uri: "{{ apigee_management_api_uri }}/organizations/{{ APIGEE_ORGANIZATION }}"
apis_api_uri: "{{ organization_api_uri }}/apis"
env_apis_api_uri: "{{ organization_api_uri}}/environments/{{ APIGEE_ENVIRONMENT }}/apis"
apigee_uri: "https://{{ APIGEE_HOSTNAME }}"
environment_subdomain: "{{ APIGEE_ENVIRONMENT }}."
api_uri: "https://{{ (APIGEE_ENVIRONMENT != 'prod') | ternary(environment_subdomain, '') }}api.service.nhs.uk/{{ SERVICE_BASE_PATH }}"
