apigee_management_api_uri: "https://api.enterprise.apigee.com/v1"
organization_api_uri: "{{ apigee_management_api_uri }}/organizations/{{ APIGEE_ORGANIZATION }}"
apis_api_uri: "{{ organization_api_uri }}/apis"
apis_apiproducts_uri: "{{ organization_api_uri }}/apiproducts"
env_apis_api_uri: "{{ organization_api_uri}}/environments/{{ APIGEE_ENVIRONMENT }}/apis"
apigee_uri: "https://{{ APIGEE_HOSTNAME }}"
environment_subdomain: "{{ APIGEE_ENVIRONMENT }}."
api_uri: "https://{{ (APIGEE_ENVIRONMENT != 'prod') | ternary(environment_subdomain, '') }}api.service.nhs.uk/{{ SERVICE_BASE_PATH }}"
proxies_non_int:
  - "{{ SERVICE_NAME }}"
  - "identity-service-{{ APIGEE_ENVIRONMENT }}"
proxies_int:
  - "{{ SERVICE_NAME }}"
  - "identity-service-{{ APIGEE_ENVIRONMENT }}"
  - "identity-service-{{ APIGEE_ENVIRONMENT }}-no-smartcard"
proxies: "{{ (APIGEE_ENVIRONMENT == 'int') | ternary(proxies_int, proxies_non_int) }}"
approval_type: "{{ (APIGEE_ENVIRONMENT == 'prod') | ternary('manual', 'auto') }}"
env_names:
  infra-dev: 'Infrastructure Development'
  internal-dev: 'Internal Development'
  internal-qa: 'Internal QA'
  internal-qa-sandbox: 'Internal QA Sandbox'
  ref: 'Reference'
  int: 'Integration'
  sandbox: 'Sandbox'
  prod: 'Live'
