parameters:
  - name: depends_on
    type: object
  - name: stage_name
  - name: apigee_organization
  - name: environment
    values:
      - internal-dev
      - internal-qa
      - internal-qa-sandbox
      - ref
      - dev
      - int
      - sandbox
      - prod
  - name: aws_env_account
  - name: aws_org_account
  - name: service_name
  - name: fully_qualified_service_name
  - name: service_base_path
  - name: secret_ids
    type: object
  - name: config_ids
    type: object
  - name: proxy_path
  - name: product_display_name
  - name: product_description
  - name: pre_template
    type: stepList
  - name: post_template
    type: stepList
  - name: pre_deploy
    type: stepList
  - name: post_deploy
    type: stepList
  - name: build_pipeline_alias


stages:
  - stage: ${{ parameters.stage_name }}
    dependsOn: ${{ parameters.depends_on }}
    jobs:
      - deployment: deploy
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - task: DownloadPipelineArtifact@2
                  inputs:
                    source: "specific"
                    project: $(resources.pipeline.${{ parameters.build_pipeline_alias }}.projectID)
                    pipeline: $(resources.pipeline.${{ parameters.build_pipeline_alias }}.pipelineID)
                    preferTriggeringPipeline: true
                    runVersion: "latestFromBranch"
                    runBranch: $(Build.SourceBranch)
                    patterns: |
                      **
                      **/*
                    path: "$(Pipeline.Workspace)/${{ parameters.service_name }}"
                - template: "../components/install-prerequisites.yml"
                - template: "../components/set-facts.yml"
                  parameters:
                    service_name: ${{ parameters.service_name }}
                    secret_ids:
                      - ${{ parameters.aws_org_account }}/azure-devops/apigee-${{ parameters.apigee_organization }}/APIGEE_OTP_KEY
                      - ${{ parameters.aws_org_account }}/azure-devops/apigee-${{ parameters.apigee_organization }}/APIGEE_PASSWORD
                      - ${{ parameters.aws_env_account }}/access-tokens/github/repo-status-update/GITHUB_ACCESS_TOKEN
                      - ${{ each secret_id in parameters.secret_ids }}:
                          - ${{ secret_id }}
                    config_ids:
                      - /${{ parameters.aws_org_account }}/azure-devops/apigee-${{ parameters.apigee_organization }}/APIGEE_USERNAME
                      - /${{ parameters.aws_env_account }}/azure-devops/env-${{ parameters.environment }}/ENV_URL
                      - /${{ parameters.aws_env_account }}/azure-devops/env-${{ parameters.environment }}/IDENTITY_URL
                      - /${{ parameters.aws_env_account }}/azure-devops/GITHUB_USER
                      - ${{ each config_id in parameters.config_ids }}:
                          - ${{ config_id }}
                - template: "../templates/deploy-service.yml"
                  parameters:
                    service_name: ${{ parameters.service_name }}
                    fully_qualified_service_name: ${{ parameters.fully_qualified_service_name }}
                    service_base_path: ${{ parameters.service_base_path }}
                    apigee_environment: ${{ parameters.environment }}
                    apigee_organization: ${{ parameters.apigee_organization }}
                    product_display_name: ${{ parameters.product_display_name }}
                    product_description: ${{ parameters.product_description }}
                    proxy_path: ${{ parameters.proxy_path }}
                    pre_template: ${{ parameters.pre_template }}
                    post_template: ${{ parameters.post_template }}
                    pre_deploy: ${{ parameters.pre_deploy }}
                    post_deploy: ${{ parameters.post_deploy }}
