parameters:
  - name: apigee_deployments
    type: object
  - name: deploy_review_sandbox
    type: boolean
  - name: spec_file
    type: string
  - name: portal_api_requires_callback_url
  - name: ping
    type: boolean
  - name: deploy_template
  - name: prod_requires_approval
  - name: manual_approval_env
    type: string
  - name: prod_producer_approval
    type: boolean



stages:
  - ${{ each apigee_deployment in parameters.apigee_deployments }}:
    - template: ./${{ parameters.deploy_template }}
      parameters:
        ${{ insert }}: ${{ apigee_deployment }}
        ${{ each param in parameters }}:
          ${{ if notIn(param.key, 'deploy_template', 'apigee_deployments', 'deploy_review_sandbox', 'prod_requires_approval', 'prod_producer_approval') }}:
            ${{ param.key }}: ${{ param.value }}

        # Compute the apigee organization & org level part of the AWS secret/config path
        ${{ if in(apigee_deployment.environment, 'internal-dev', 'internal-dev-sandbox', 'internal-qa', 'internal-qa-sandbox', 'ref', 'manual-approval') }}:
          apigee_organization: nonprod
        ${{ if in(apigee_deployment.environment, 'dev', 'int', 'sandbox', 'prod') }}:
          apigee_organization: prod

        # Compute AWS environment level prefix for secrets/config
        ${{ if notIn(apigee_deployment.environment, 'prod') }}:
          aws_account: ptl
        ${{ if in(apigee_deployment.environment, 'prod') }}:
          aws_account: prod

        # deploy_review_sandbox not for release pipeline, for now
        ${{ if eq(parameters.deploy_template, 'pr.yml')}}:
          deploy_review_sandbox: ${{ parameters.deploy_review_sandbox }}
          pr_label: pr-${{ replace(replace(replace(variables['Build.SourceBranch'], '/merge', ''), 'refs/pull/', ''), '/', '_') }}

        # if Release pipeline use friendly api name for api portal
        ${{ if eq(parameters.deploy_template, 'release.yml') }}:
          friendly_api_name: ${{ apigee_deployment.product_display_name }}
