parameters:
  - name: stage_name
  - name: depends_on
    type: object
  - name: manual_approval_env
    type: string

stages:
  - stage: ${{ parameters.stage_name }}
    dependsOn: ${{ parameters.depends_on }}
    jobs:
      - deployment: deploy
        displayName: Manual Approval Required
        pool:
          vmImage: "Ubuntu-16.04"
        environment: ${{ parameters.manual_approval_env }}
        strategy:
          runOnce:
            deploy:
              steps:
                - bash: |
                    echo Approved