parameters:
  - name: environment
    type: string
    values:
      - internal-dev
  - name: apigee_organization
  - name: aws_org_account
  - name: aws_env_account
  - name: stage_name
  - name: service_name
  - name: short_service_name
  - name: service_base_path
  - name: product_display_name
  - name: product_description
  - name: fully_qualified_service_name
  - name: proxy_path
  - name: secret_ids
    type: object
  - name: config_ids
    type: object
  - name: pre_template
    type: stepList
  - name: post_template
    type: stepList
  - name: pre_deploy
    type: stepList
  - name: post_deploy
    type: stepList
  - name: deploy_review_sandbox
    type: boolean
  - name: spec_file
    type: string
  - name: portal_api_requires_callback_url
    type: boolean
  - name: make_spec_visible
    type: boolean
  - name: depends_on
    type: object
  - name: jinja_templates
    type: object
  - name: ping
    type: boolean
  - name: friendly_api_name
    type: string
    default: ''

stages:
  - template: ./deploy-stage.yml
    parameters:
      fully_qualified_service_name: ${{ parameters.service_name }}-pr-${{ replace(replace(replace(variables['Build.SourceBranch'], '/merge', ''), 'refs/pull/', ''), '/', '_') }}
      service_base_path: ${{ parameters.service_base_path }}-pr-${{ replace(replace(replace(variables['Build.SourceBranch'], '/merge', ''), 'refs/pull/', ''), '/', '_') }}
      ${{ each param in parameters }}:
        ${{ if notIn(param.key, 'deploy_review_sandbox', 'fully_qualified_service_name', 'service_base_path') }}:
          ${{ param.key }}: ${{ param.value }}
