parameters:
  - name: environment
    type: string
    values:
      - internal-dev
  - name: apigee_organization
  - name: aws_org_account
  - name: aws_env_account
  - name: stage_name
  - name: service_name
  - name: short_service_name
  - name: service_base_path
  - name: product_display_name
  - name: product_description
  - name: fully_qualified_service_name
  - name: proxy_path
  - name: secret_ids
    type: object
  - name: config_ids
    type: object
  - name: pre_template
    type: stepList
  - name: post_template
    type: stepList
  - name: pre_deploy
    type: stepList
  - name: post_deploy
    type: stepList
  - name: pr_proxy_deploy_steps
    type: object
  - name: pr_sandbox_deploy_steps
    type: object
  - name: deploy_review_sandbox
    type: boolean
  - name: spec_file
    type: string
  - name: portal_api_requires_callback_url
    type: boolean
  - name: make_spec_visible
    type: boolean
  - name: depends_on
    type: object
  - name: jinja_templates
    type: object
  - name: friendly_api_name
    type: string
    default: ''

stages:
  - ${{ if eq(parameters.stage_name, 'internal_dev') }}:
    - template: ./deploy-stage.yml
      parameters:
        notify: true
        fully_qualified_service_name: ${{ parameters.service_name }}-pr-${{ replace(replace(replace(variables['Build.SourceBranch'], '/merge', ''), 'refs/pull/', ''), '/', '_') }}
        service_base_path: ${{ parameters.service_base_path }}-pr-${{ replace(replace(replace(variables['Build.SourceBranch'], '/merge', ''), 'refs/pull/', ''), '/', '_') }}
        ${{ each param in parameters }}:
          ${{ if in(param.key, 'pr_proxy_deploy_steps') }}:
            ${{ each step_list in parameters.pr_proxy_deploy_steps }}:
              ${{ if eq(step_list.key, 'pre_template') }}:
                pre_template: ${{ step_list.value }}
                ${{ if notIn(param.key, 'deploy_review_sandbox', 'fully_qualified_service_name', 'service_base_path', 'pr_proxy_deploy_steps', 'pr_sandbox_deploy_steps', 'pre_template') }}:
                  ${{ param.key }}: ${{ param.value }}
              ${{ if eq(step_list.key, 'post_template') }}:
                post_template: ${{ step_list.value }}
                ${{ if notIn(param.key, 'deploy_review_sandbox', 'fully_qualified_service_name', 'service_base_path', 'pr_proxy_deploy_steps', 'pr_sandbox_deploy_steps', 'post_template') }}:
                  ${{ param.key }}: ${{ param.value }}
              ${{ if eq(step_list.key, 'pre_deploy') }}:
                pre_deploy: ${{ step_list.value }}
                ${{ if notIn(param.key, 'deploy_review_sandbox', 'fully_qualified_service_name', 'service_base_path', 'pr_proxy_deploy_steps', 'pr_sandbox_deploy_steps', 'pre_deploy') }}:
                  ${{ param.key }}: ${{ param.value }}
              ${{ if eq(step_list.key, 'post_deploy') }}:
                post_deploy: ${{ step_list.value }}
                ${{ if notIn(param.key, 'deploy_review_sandbox', 'fully_qualified_service_name', 'service_base_path', 'pr_proxy_deploy_steps', 'pr_sandbox_deploy_steps', 'post_deploy') }}:
                  ${{ param.key }}: ${{ param.value }}
          ${{ if notIn(param.key, 'pr_proxy_deploy_steps') }}:
            ${{ if notIn(param.key, 'deploy_review_sandbox', 'fully_qualified_service_name', 'service_base_path', 'pr_proxy_deploy_steps', 'pr_sandbox_deploy_steps') }}:
              ${{ param.key }}: ${{ param.value }}
    - ${{ if parameters.deploy_review_sandbox }}:
      - template: ./deploy-stage.yml
        parameters:
          fully_qualified_service_name: ${{ parameters.service_name }}-pr-${{ replace(replace(replace(variables['Build.SourceBranch'], '/merge', ''), 'refs/pull/', ''), '/', '_') }}-sandbox
          service_base_path: ${{ parameters.service_base_path }}-pr-${{ replace(replace(replace(variables['Build.SourceBranch'], '/merge', ''), 'refs/pull/', ''), '/', '_') }}-sandbox
          stage_name: ${{ parameters.stage_name }}_sandbox
          ${{ each param in parameters }}:
          ${{ if in(param.key, 'pr_sandbox_deploy_steps') }}:
            ${{ each step_list in parameters.pr_sandbox_deploy_steps }}:
              ${{ if eq(step_list.key, 'pre_template') }}:
                pre_template: ${{ step_list.value }}
                ${{ if notIn(param.key, 'deploy_review_sandbox', 'fully_qualified_service_name', 'service_base_path', 'pr_proxy_deploy_steps', 'pr_sandbox_deploy_steps', 'pre_template') }}:
                  ${{ param.key }}: ${{ param.value }}
              ${{ if eq(step_list.key, 'post_template') }}:
                post_template: ${{ step_list.value }}
                ${{ if notIn(param.key, 'deploy_review_sandbox', 'fully_qualified_service_name', 'service_base_path', 'pr_proxy_deploy_steps', 'pr_sandbox_deploy_steps', 'post_template') }}:
                  ${{ param.key }}: ${{ param.value }}
              ${{ if eq(step_list.key, 'pre_deploy') }}:
                pre_deploy: ${{ step_list.value }}
                ${{ if notIn(param.key, 'deploy_review_sandbox', 'fully_qualified_service_name', 'service_base_path', 'pr_proxy_deploy_steps', 'pr_sandbox_deploy_steps', 'pre_deploy') }}:
                  ${{ param.key }}: ${{ param.value }}
              ${{ if eq(step_list.key, 'post_deploy') }}:
                post_deploy: ${{ step_list.value }}
                ${{ if notIn(param.key, 'deploy_review_sandbox', 'fully_qualified_service_name', 'service_base_path', 'pr_proxy_deploy_steps', 'pr_sandbox_deploy_steps', 'post_deploy') }}:
                  ${{ param.key }}: ${{ param.value }}
          ${{ if notIn(param.key, 'pr_sandbox_deploy_steps') }}:
            ${{ if notIn(param.key, 'deploy_review_sandbox', 'fully_qualified_service_name', 'service_base_path', 'pr_proxy_deploy_steps', 'pr_sandbox_deploy_steps') }}:
              ${{ param.key }}: ${{ param.value }}
