parameters:
  - name: environment
    type: string
    values:
      - internal-dev
      - internal-dev-sandbox
  - name: apigee_organization
  - name: aws_org_account
  - name: aws_env_account
  - name: stage_name
  - name: service_name
  - name: short_service_name
  - name: friendly_api_name
    default: ''
  - name: service_base_path
  - name: product_display_name
  - name: product_description
  - name: fully_qualified_service_name
  - name: proxy_path
  - name: pr_label
  - name: enable_monitoring
    type: boolean
  - name: secret_ids
    type: object
  - name: config_ids
    type: object
  - name: pre_template
    type: stepList
  - name: post_template
    type: stepList
  - name: pre_deploy
    type: stepList
  - name: post_deploy
    type: stepList
  - name: deploy_review_sandbox
    type: boolean
  - name: deploy_test_app
    type: boolean
  - name: test_app_callback_url
    type: string
  - name: spec_file
  - name: portal_api_requires_callback_url
    type: boolean
  - name: make_spec_visible
    type: boolean
  - name: depends_on
    type: object
  - name: jinja_templates
    type: object
  - name: ping
    type: boolean

stages:
  - template: ./deploy-stage.yml
    parameters:
      ${{ if eq(parameters.proxy_path, 'live')}}:
        fully_qualified_service_name: ${{ parameters.service_name }}-${{ parameters.pr_label }}
      ${{ if ne(parameters.proxy_path, 'live')}}:
        fully_qualified_service_name: ${{ parameters.service_name }}-${{ parameters.pr_label }}-${{ parameters.proxy_path }}
      service_base_path: ${{ parameters.service_base_path }}-${{ parameters.pr_label }}
      notify: true
      ${{ each param in parameters }}:
        ${{ if notIn(param.key, 'deploy_review_sandbox', 'fully_qualified_service_name', 'service_base_path', 'pr_label') }}:
          ${{ param.key }}: ${{ param.value }}
