
- name: fail for prod environment
  fail:
    msg: "this is deprecated and shouldn't ever be executed for a production api"
  when: APIGEE_ENVIRONMENT == 'prod'

- name: fail for prod account
  fail:
    msg: "this is deprecated and shouldn't ever be executed for a production api"
  when: account == 'prod'

- name: check if user exists
  command: "{{ aws_cmd }} iam get-user --user-name {{ deploy_user_name }} --query User"
  register: get_user
  changed_when: no

- name: check for access key secret
  command: "{{ aws_cmd }} secretsmanager describe-secret --secret-id {{ deploy_user_secret }}"
  register: describe_secret
  changed_when: no
  failed_when: describe_secret.rc !=0 and 'ResourceNotFoundException' not in describe_secret.stderr

- name: create an access key
  command: "{{ aws_cmd }} iam create-access-key --user-name {{ deploy_user_name }} --query AccessKey"
  register: create_access_key
  when: describe_secret.rc == 255

- name: parse access key
  set_fact:
    access_key: "{{ create_access_key.stdout | from_json }}"
  when: describe_secret.rc == 255

- name: create access token secret
  block:

    - name: write aws config
      copy:
        content: |
          [profile {{ deploy_user_name }}]
          aws_access_key_id = {{ access_key.AccessKeyId }}
          aws_secret_access_key = {{ access_key.SecretAccessKey }}
          region = eu-west-2
          output = json
        dest: "~/.tmp-aws-config"
        mode: 0400

    - name: create secret
      command: "{{ aws_cmd }} secretsmanager create-secret --name {{ deploy_user_secret }} --secret-string file://~/.tmp-aws-config"

  when: describe_secret.rc == 255
  always:
    - name: remove temp aws config
      file:
        path: "~/.tmp-aws-config"
        state: absent
