
- name: extract vars
  set_fact:
    apigee_environment: "{{ ns_service_tuple.0 }}"
    namespaced_name: "{{ ns_service_tuple.1 }}"
    service_id: "{{  ns_service_tuple.2 }}"
    pr_number: "{{ ns_service_tuple.1 |  regex_replace('^' + ns_service_tuple.2 + '-', '')  }}"

- name: check api_environment
  fail:
    msg: "unsupport API environment {{ apigee_environment }}"
  when: APIGEE_ENVIRONMENT not in ('internal-dev', 'internal-dev-sandbox')

- name: check pr_number
  fail:
    msg: "pr_number not set"
  when: not pr_number

- name: get service created at
  shell: >
    set -o pipefail;
    {{ aws_cmd }} ecs describe-services --cluster apis-{{ apigee_environment }}
    --services {{ namespaced_name }} --query services[0].createdAt | sed 's#null#1577836800#' | xargs -i date --utc -d @{} '+%FT%TZ'
  args:
    executable: /bin/bash
  register: get_service_created_at
  changed_when: no

- name: parse_created_at
  set_fact:
    should_remove: >-
      {{
        (
          (
            (ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ')) -
            (get_service_created_at.stdout | to_datetime('%Y-%m-%dT%H:%M:%SZ'))
          ).total_seconds() / 3600
        ) >= (retain_hours | int)
      }}
    age_hours: >-
      {{
        (
          (
            (ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ')) -
            (get_service_created_at.stdout | to_datetime('%Y-%m-%dT%H:%M:%SZ'))
          ).total_seconds() / 3600
        )
      }}

# left these in to print some useful info about each service
- debug: msg="processing service - {{ apigee_environment }} - {{ service_id }} - pr - {{ pr_number }}"
- debug: msg="created at, {{ get_service_created_at.stdout }}"
- debug: msg="current_date, {{ ansible_date_time.iso8601 }}"
- debug: msg="age_hours, {{ age_hours }}"
- debug: msg="should remove,  {{ should_remove }}"

- name: "remove ecs service {{ apigee_environment }} - {{ service_id }} - pr - {{ pr_number }}"
  include_role:
    name: destroy-ecs-proxies
  when: should_remove
