---
sub_workspace: "{{ ':' + pr_number if pr_number else '' }}"
namespaced_name: "{{ service_id }}{{ '-' + pr_number if pr_number else '' }}"
workspace: "api-deployment:{{ account }}:{{ apigee_environment }}:{{ service_id }}{{ sub_workspace }}"
do_not_terraform: "{{ lookup('env','do_not_terraform') }}"
