---
service_base_path: "{{ SERVICE_BASE_PATH | regex_replace('^\\/|\\/$', '') }}"
sub_workspace: "{{ ':' + _NAMESPACE if _NAMESPACE else '' }}"
workspace: "api-deployment:{{ account }}:{{ apigee_environment }}:{{service_name}}{{ sub_workspace }}"
namespaced_name: "{{service_name}}{{ '-' + _NAMESPACE if _NAMESPACE else '' }}"
