---

aws_region: "eu-west-2"
service_name: "{{ SERVICE_NAME | lower }}"
aws_cmd: "aws --profile={{ aws_profile }} --region={{ aws_region }}"
apigee_access_token: "{{ lookup('env','API_ACCESS_TOKEN') }}"
env_apigee_org: "{{ lookup('env','API_ORG') }}"
namespace: