- name: add azure devops extension
  command: az extension add --name azure-devops

- name: set organization and project defaults
  shell: az devops configure --defaults organization="https://dev.azure.com/{{ ORG }}" project="{{ PROJECT }}"

- name: login to azure
  shell: az login

- name: create pipelines folder
  shell: az pipelines folder create --path "/{{ PREFIX }}"

- name: create build pipeline
  shell: >
    az pipelines create 
    --name "{{ PREFIX }}-Build" 
    --repository {{ REPO }} 
    --repository-type github 
    --folder-path "/{{ PREFIX }}" 
    --service-connection {{ SERVICE_CONNECTION }} 
    --branch master 
    --yaml-path azure/azure-build-pipeline.yml

- name: create pull request pipeline
  shell: >
    az pipelines create 
    --name "{{ PREFIX }}-Pull-Request" 
    --repository {{ REPO }} 
    --repository-type github 
    --folder-path "/{{ PREFIX }}" 
    --service-connection {{ SERVICE_CONNECTION }} 
    --branch master
    --yaml-path azure/azure-pr-pipeline.yml
    --skip-first-run true

- name: create release pipeline
  shell: >
    az pipelines create 
    --name "{{ PREFIX }}-Release" 
    --repository {{ REPO }} 
    --repository-type github 
    --folder-path "/{{ PREFIX }}" 
    --service-connection {{ SERVICE_CONNECTION }} 
    --branch master 
    --yaml-path azure/azure-release-pipeline.yml
    --skip-first-run true