- name: parse_created_at
  set_fact:
    should_remove: >-
      {{
        (
          (
            (ansible_date_time.epoch | int) - (item.modified / 1000)
          ) / 3600
        ) >= (retain_hours | int)
      }}
    age_hours: >-
      {{
        (
          (
            (ansible_date_time.epoch | int) - (item.modified / 1000)
          ) / 3600
        )
      }}

- debug:
    msg:
      - "apiId, {{ item.apiId }}"
      - "modified at, {{ item.modified / 1000 }}"
      - "current_date, {{ ansible_date_time.epoch | int }}"
      - "age_hours, {{ age_hours }}"
      - "should remove,  {{ should_remove }}"

- debug:
    msg: "Removing {{ item.apiId }}"
  when: should_remove

- name: remove pr portal api
  uri:
    url: "{{ portals_base_uri }}/{{ portal_id }}/apidocs/{{ item.id }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ APIGEE_ACCESS_TOKEN }}"
  when: should_remove
