
- name: "get apps"
  uri:
    url: "{{ apps_uri }}?expand=true"
    headers:
      Authorization: "Bearer {{ APIGEE_ACCESS_TOKEN }}"
    return_content: yes
    timeout: 90
  register: get_apps

- name: create product map
  set_fact:
    product_app_map: "{{ get_apps.json.app | apigee_apps_to_product_map(product_filter='.*-pr-[0-9]+.*') }}"

- name: get products
  uri:
    url: "{{ products_uri }}"
    headers:
      Authorization: "Bearer {{ APIGEE_ACCESS_TOKEN }}"
    return_content: yes
  register: products

# The exception list for - reject('match', 'e-referrals-service-api-alpha-pr-126.*') - Is a pre-agreed and temporary solution.
# This should be taken out once it is no longer needed.
# No other exceptions should be added
- name: filter products
  set_fact:
    pr_products: "{{  products.json | select('match', '.*-pr-[0-9]+.*') | reject('match', 'e-referrals-service-api-alpha-pr-126.*') }}"

- name: remove pr products
  include_tasks: remove-product.yml
  loop: "{{ pr_products }}"
  loop_control:
    loop_var: "product_slug"
