
- name: check for access key secret
  command: "{{ aws_cmd }} secretsmanager describe-secret --secret-id {{ build_user_secret }}"
  register: describe_secret
  changed_when: no
  failed_when: describe_secret.rc !=0 and 'ResourceNotFoundException' not in describe_secret.stderr

- name: remove access key secret
  command: >
    {{ aws_cmd }} secretsmanager delete-secret  --secret-id {{ build_user_secret }} --force-delete-without-recovery
  register: create_access_key
  when: describe_secret.rc == 0

- name: check if user exists
  command: "{{ aws_cmd }} iam get-user --user-name {{ build_user_name }} --query User"
  register: get_user
  changed_when: no
  failed_when: get_user.rc !=0 and 'NoSuchEntity' not in get_user.stderr

- name: list user policies
  command: "{{ aws_cmd }}  iam list-user-policies --user-name {{ build_user_name }} --query PolicyNames"
  register: list_user_policies
  changed_when: no
  when: get_user.rc == 0

- name: parse policies json
  set_fact:
    user_policies: "{{ list_user_policies.stdout | from_json }}"
  when: get_user.rc == 0

- name: delete user policy
  command: "{{ aws_cmd }} iam delete-user-policy --user-name {{ build_user_name }} --policy-name {{ item }}"
  with_items: "{{ user_policies }}"
  when: get_user.rc == 0

- name: list access keys
  command: "{{ aws_cmd }}  iam list-access-keys --user-name {{ build_user_name }} --query AccessKeyMetadata"
  register: list_acess_keys
  changed_when: no
  when: get_user.rc == 0

- name: parse access keys
  set_fact:
    access_keys: "{{ list_acess_keys.stdout | from_json }}"
  when: get_user.rc == 0

- name: delete access key
  command: "{{ aws_cmd }} iam  delete-access-key --user-name {{ build_user_name }} --access-key-id {{ item.AccessKeyId }}"
  with_items: "{{ access_keys }}"
  when: get_user.rc == 0

- name: delete iam user
  command: "{{ aws_cmd }} iam delete-user --user-name {{ build_user_name }} --query User"
  when: get_user.rc == 0
