- name: get specs
  uri:
    url: "{{ specs_list_uri }}"
    headers:
      Authorization: "Bearer {{ APIGEE_ACCESS_TOKEN }}"
    return_content: yes
  register: specs

- name: set spec_filter
  set_fact:
    spec_filter: "{{ specs.json.contents | to_json | from_json | json_query(item) }}"
  with_items: 
    - "[?contains(apiId, {{ SERVICE_NAME }} )]"
    - "[?contains(apiId, {{ SERVICE_NAME_SHORT }} )]"
  register: search_result

- name: make a list and set portal_api
  set_fact:
    target_specs: "{{ search_result.results | map(attribute='ansible_facts.spec_filter') | list | flatten }}"

- name: determine whether to remove
  include_tasks: remove-target-spec.yml
  loop: "{{ target_specs }}"
