- name: get specs
  uri:
    url: "{{ specs_list_uri }}"
    headers:
      Authorization: "Bearer {{ APIGEE_ACCESS_TOKEN }}"
    return_content: yes
  register: specs

- name: set spec_filter
  set_fact:
    spec_filter: "{{ specs.json.contents | to_json | from_json | json_query(regex) }}"
  register: search_result

- name: make a list and set portal_api
  set_fact:
    target_specs: "{{ search_result.results | map(attribute='ansible_facts.spec_filter') | list | flatten }}"

- name: "removing spec {{ item.name }}"
  uri:
    url: "{{ specs_resource_uri }}/{{ item.id }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ APIGEE_ACCESS_TOKEN }}"
  changed_when: yes
