
parameters:
  - name: 'role'
    type: string


steps:
    - bash: |
        set -e
        mkdir -p ~/.aws
        rm -f ~/.aws/config || true
        echo '[default]' > ~/.aws/config
        echo 'region = eu-west-2' >> ~/.aws/config
        echo 'output = json' >> ~/.aws/config
        chmod 600 ~/.aws/config
        cp ~/.aws/config ~/.aws/config.default
      displayName: clean aws config

    - bash: |
        set -e

        aws_role="{{ parameters.role }}"
        if [[ "${aws_role}" != aws:aws:iam:* ]]; then
            account_id="$(aws sts get-caller-identity --query Account --output text)"
            aws_role="arn:aws:iam::${account_id}:role/${aws_role}"
        fi

        cp ~/.aws/config.default ~/.aws/config
        tmp_file="$(Agent.TempDirectory)/.aws.tmp.creds.json"
        aws sts assume-role --role-arn "${aws_role}" --role-session-name build-assume-role > ${tmp_file}

        echo "aws_access_key_id = $(jq -r .Credentials.AccessKeyId ${tmp_file})" >> ~/.aws/config
        echo "aws_secret_access_key = $(jq -r .Credentials.SecretAccessKey ${tmp_file})" >> ~/.aws/config
        echo "aws_session_token = $(jq -r .Credentials.SessionToken ${tmp_file})" >> ~/.aws/config