parameters:
  - name: expose
    type: object
    default: []

steps:
  - ${{ each param in parameters.expose }}:
    - bash: |
        set -euo pipefail
        export VARIABLE_NAME="`echo ${{ param.key }} | tr a-z A-Z`"
        echo "##vso[task.setvariable variable=${VARIABLE_NAME}]${{ param.value }}"
      displayName: Expose ${{ param.key }} as variable