- name: build-ecr-images
  hosts: 127.0.0.1
  connection: local
  gather_facts: no

  vars:
    service_id: "{{ lookup('env','service_id') }}"
    aws_profile: "build-{{ service_id | lower }}"

  pre_tasks:

    - name: check service_id
      fail:
        msg: "service_id not set"
      when: not service_id

    - name: include vars
      include_vars:
        file: "{{ lookup('env', 'CONTAINER_VARS_FILE') | expandvars | expanduser | realpath }}"

  roles:
    - setup-facts
    - build-ecs-proxies