- name: build-ecr-images
  hosts: 127.0.0.1
  connection: local
  gather_facts: yes

  vars:
    SERVICE_NAME: "{{ lookup('env','SERVICE_NAME') }}"
    aws_profile: "build-{{ service_name | lower }}"

  pre_tasks:

    - name: check SERVICE_NAME
      fail:
        msg: "SERVICE_NAME not set"
      when: not SERVICE_NAME

    - name: include vars
      include_vars:
        file: "{{ playbook_dir }}/../../ecs-proxies.yml"

  roles:
    - setup-facts
    - build-ecs-proxies