- name: build-ecr-images
  hosts: 127.0.0.1
  connection: local
  gather_facts: yes

  vars:
    SERVICE_NAME: "{{ lookup('env','SERVICE_NAME') }}"
    SERVICE_BASE_PATH:  "{{ lookup('env','SERVICE_BASE_PATH') }}"
    APIGEE_ENVIRONMENT: "{{ lookup('env', 'APIGEE_ENVIRONMENT') }}"
    APIGEE_HOSTNAME: "{{ '' if APIGEE_ENVIRONMENT == 'prod' else APIGEE_ENVIRONMENT + '.' }}api.service.nhs.uk"
    aws_cmd: "aws --profile=deploy-{{ service_name }}-{{ APIGEE_ENVIRONMENT }} --region=eu-west-2"

  pre_tasks:
    - name: check SERVICE_BASE_PATH
      fail:
        msg: "SERVICE_BASE_PATH not set"
      when: not SERVICE_BASE_PATH

    - name: check SERVICE_NAME
      fail:
        msg: "SERVICE_NAME not set"
      when: not SERVICE_NAME

    - name: check APIGEE_ENVIRONMENT
      fail:
        msg: "APIGEE_ENVIRONMENT not set"
      when: not APIGEE_ENVIRONMENT


  roles:
    - setup-facts
    - deploy-proxy-ecs