- name: build-ecr-images
  hosts: 127.0.0.1
  connection: local
  gather_facts: yes

  vars:
    service_basename: "{{ lookup('env','service_basename') }}"
    aws_profile: "build-{{ service_name | lower }}"

  pre_tasks:

    - name: check service_basename
      fail:
        msg: "service_basename not set"
      when: not service_basename

    - name: include vars
      include_vars:
        file: "{{ lookup('env', 'CONTAINER_VARS_FILE') | expandvars | expanduser | realpath }}"

  roles:
    - setup-facts
    - build-ecs-proxies