- name: create api deployment pre-reqs
  hosts: 127.0.0.1
  connection: local
  gather_facts: no

  vars:
    APIGEE_ENVIRONMENT: "{{ lookup('env','APIGEE_ENVIRONMENT') }}"
    SHORT_SERVICE_NAME: "{{ lookup('env','SHORT_SERVICE_NAME') }}"
    apigee_environment: "{{ APIGEE_ENVIRONMENT }}"
    short_service_name: "{{ SHORT_SERVICE_NAME }}"
    service_id: "{{ lookup('env','service_id') }}"
    pr_number: "{{ lookup('env','pr_number') }}"
    account:  "{{ lookup('env','account') }}"
    aws_profile: "apm_{{ account }}"

  pre_tasks:

    - name: check account
      fail:
        msg: "account not set"
      when: not account

    - name: check service_id
      fail:
        msg: "service_id not set"
      when: not service_id

    - name: check APIGEE_ENVIRONMENT
      fail:
        msg: "APIGEE_ENVIRONMENT not set"
      when: not APIGEE_ENVIRONMENT

    - name: check SHORT_SERVICE_NAME
      fail:
        msg: "SHORT_SERVICE_NAME not set"
      when: not SHORT_SERVICE_NAME

  roles:
    - setup-facts
    - create-api-deployment-pre-reqs
