- name: create ecr build user
  hosts: 127.0.0.1
  connection: local
  gather_facts: yes

  vars:
    service_basename: "{{ lookup('env','service_basename') }}"
    account: "{{ lookup('env','account') }}"
    aws_profile: "apm_{{ account }}"

  pre_tasks:

    - name: check account
      fail:
        msg: "account not set"
      when: not account

    - name: check service_basename
      fail:
        msg: "service_basename not set"
      when: not service_basename


  roles:
    - setup-facts
    - create-ecr-build-user