- name: create api deployment user access key
  hosts: 127.0.0.1
  connection: local
  gather_facts: yes

  vars:
    service_basename: "{{ lookup('env','service_basename') }}"
    SERVICE_BASE_PATH:  "{{ lookup('env','SERVICE_BASE_PATH') }}"
    APIGEE_ENVIRONMENT: "{{ lookup('env', 'APIGEE_ENVIRONMENT') }}"
    APIGEE_HOSTNAME: "{{ '' if APIGEE_ENVIRONMENT == 'prod' else APIGEE_ENVIRONMENT + '.' }}api.service.nhs.uk"

  pre_tasks:
    - name: check SERVICE_BASE_PATH
      fail:
        msg: "SERVICE_BASE_PATH not set"
      when: not SERVICE_BASE_PATH

    - name: check service_basename
      fail:
        msg: "service_basename not set"
      when: not service_basename

    - name: check APIGEE_ENVIRONMENT
      fail:
        msg: "APIGEE_ENVIRONMENT not set"
      when: not APIGEE_ENVIRONMENT


  roles:
    - setup-facts
    - create-api-deployment-user-access-key