- name: build-ecr-images
  hosts: 127.0.0.1
  connection: local
  gather_facts: yes

  vars:
    SERVICE_NAME: "{{ lookup('env','SERVICE_NAME') }}"
    APIGEE_ENVIRONMENT: "{{ lookup('env','APIGEE_ENVIRONMENT') }}"
    SERVICE_BASE_PATH:  "{{ lookup('env','SERVICE_BASE_PATH') }}"
    _NAMESPACE: "{{ lookup('env','_NAMESPACE') }}"
    APIGEE_HOSTNAME: "{{ '' if APIGEE_ENVIRONMENT == 'prod' else APIGEE_ENVIRONMENT + '.' }}api.service.nhs.uk"
    apigee_uri: "https://{{ APIGEE_HOSTNAME }}"
    account:  "{{ lookup('env','account') }}"
    sub_namespace: "{{ '-' + _NAMESPACE if _NAMESPACE else '' }}"
    aws_profile: "deploy-{{ APIGEE_ENVIRONMENT | lower }}-{{ SERVICE_NAME | lower }}{{ sub_namespace }}"


  pre_tasks:

    - name: check account
      fail:
        msg: "account not set"
      when: not account

    - name: check SERVICE_NAME
      fail:
        msg: "SERVICE_NAME not set"
      when: not SERVICE_NAME

    - name: check APIGEE_ENVIRONMENT
      fail:
        msg: "APIGEE_ENVIRONMENT not set"
      when: not APIGEE_ENVIRONMENT

    - name: check SERVICE_BASE_PATH
      fail:
        msg: "SERVICE_BASE_PATH not set"
      when: not SERVICE_BASE_PATH

    - name: include vars
      include_vars:
        file: "{{ playbook_dir }}/../../ecs-proxies.yml"

  roles:
    - setup-facts
    - deploy-ecs-proxies