- name: deploy ecs proxies
  hosts: 127.0.0.1
  connection: local
  gather_facts: no

  vars:
    account:  "{{ lookup('env','account') }}"
    service_id: "{{ lookup('env','service_id') }}"
    APIGEE_ENVIRONMENT: "{{ lookup('env','APIGEE_ENVIRONMENT') }}"
    pr_number: "{{ lookup('env','pr_number') }}"
    APIGEE_HOSTNAME: "{{ '' if APIGEE_ENVIRONMENT == 'prod' else APIGEE_ENVIRONMENT + '.' }}api.service.nhs.uk"
    SERVICE_BASE_PATH: "{{ lookup('env', 'SERVICE_BASE_PATH' )}}"
    DEPLOYED_VERSION: "{{ lookup('env', 'DEPLOYED_VERSION') }}"
    RELEASE_RELEASEID: "{{ lookup('env', 'RELEASE_RELEASEID') }}"
    SOURCE_COMMIT_ID: "{{ lookup('env', 'SOURCE_COMMIT_ID') }}"
    apigee_uri: "https://{{ APIGEE_HOSTNAME }}"
    aws_profile: "deploy-{{ APIGEE_ENVIRONMENT | lower }}-{{ service_id }}"


  pre_tasks:

    - name: check account
      fail:
        msg: "account not set"
      when: not account

    - name: check service_id
      fail:
        msg: "service_id not set"
      when: not service_id

    - name: check APIGEE_ENVIRONMENT
      fail:
        msg: "APIGEE_ENVIRONMENT not set"
      when: not APIGEE_ENVIRONMENT

    - name: check SERVICE_BASE_PATH
      fail:
        msg: "SERVICE_BASE_PATH not set"
      when: not SERVICE_BASE_PATH

    - name: include vars
      include_vars:
        file: "{{ lookup('env', 'PROXY_VARS_FILE') | expandvars | expanduser | realpath }}"

  roles:
    - setup-facts
    - deploy-ecs-proxies