- name: "deploy apigee proxy"
  hosts: 127.0.0.1
  connection: local
  gather_facts: no

  vars:
    SERVICE_NAME: "{{ lookup('env', 'SERVICE_NAME') }}"
    APIGEE_ENVIRONMENT: "{{ lookup('env','APIGEE_ENVIRONMENT') }}"
    APIGEE_ORGANIZATION: "{{ lookup('env', 'APIGEE_ORGANIZATION') }}"
    APIGEE_ACCESS_TOKEN: "{{ lookup('env', 'APIGEE_ACCESS_TOKEN') }}"
    SPEC_FILE: "{{ lookup('env', 'SPEC_FILE') | default('', True) }}"
    FRIENDLY_NAME: "{{ lookup('env', 'FRIENDLY_NAME') }}"
    PRODUCT_DISPLAY_NAME: "{{ lookup('env', 'PRODUCT_DISPLAY_NAME') }}"
    PRODUCT_DESCRIPTION: "{{ lookup('env', 'PRODUCT_DESCRIPTION') }}"
    VISIBLE: "{{ lookup('env', 'VISIBLE') }}"
    REQUIRE_CALLBACK_URL: "{{ lookup('env', 'REQUIRE_CALLBACK_URL') }}"

  pre_tasks:
    - name: check SERVICE_NAME
      fail:
        msg: "SERVICE_NAME not set"
      when: not SERVICE_NAME

    - name: check APIGEE_ENVIRONMENT
      fail:
        msg: "APIGEE_ENVIRONMENT not set"
      when: not APIGEE_ENVIRONMENT

    - name: check APIGEE_ORGANIZATION
      fail:
        msg: "APIGEE_ORGANIZATION not set"
      when: not APIGEE_ORGANIZATION

    - name: check APIGEE_ACCESS_TOKEN
      fail:
        msg: "APIGEE_ACCESS_TOKEN not set"
      when: not APIGEE_ACCESS_TOKEN

    - name: check PRODUCT_DISPLAY_NAME
      fail:
        msg: "PRODUCT_DISPLAY_NAME not set"
      when: not PRODUCT_DISPLAY_NAME

    - name: check PRODUCT_DESCRIPTION
      fail:
        msg: "PRODUCT_DESCRIPTION not set"
      when: not PRODUCT_DESCRIPTION

    - name: check FRIENDLY_NAME
      fail:
        msg: "FRIENDLY_NAME not set"
      when: not FRIENDLY_NAME

    - name: check VISIBLE
      fail:
        msg: "VISIBLE not True or False"
      when: (VISIBLE != False) and (VISIBLE != True)

    - name: check REQUIRE_CALLBACK_URL
      fail:
        msg: "REQUIRE_CALLBACK_URL not True or False"
      when: (REQUIRE_CALLBACK_URL != False) and (REQUIRE_CALLBACK_URL != True)
  roles:
    - deploy-apigee-product-and-spec
