- name: "deploy apigee proxy"
  hosts: 127.0.0.1
  connection: local
  gather_facts: no

  vars:
    SERVICE_NAME: "{{ lookup('env', 'SERVICE_NAME') }}"
    SERVICE_BASE_PATH: "{{ lookup('env', 'SERVICE_BASE_PATH') }}"
    APIGEE_ENVIRONMENT: "{{ lookup('env','APIGEE_ENVIRONMENT') }}"
    APIGEE_ORGANIZATION: "{{ lookup('env', 'APIGEE_ORGANIZATION') }}"
    APIGEE_ACCESS_TOKEN: "{{ lookup('env', 'APIGEE_ACCESS_TOKEN') }}"
    PROXY_DIR: "{{ lookup('env', 'PROXY_DIR') }}"
    PING: "{{ (lookup('env', 'PING') | length > 0) | ternary(lookup('env', 'PING'), 'true') }}"

  pre_tasks:
    - name: check SERVICE_NAME
      fail:
        msg: "SERVICE_NAME not set"
      when: not SERVICE_NAME

    - name: check SERVICE_BASE_PATH
      fail:
        msg: "SERVICE_BASE_PATH not set"
      when: not SERVICE_BASE_PATH

    - name: check APIGEE_ENVIRONMENT
      fail:
        msg: "APIGEE_ENVIRONMENT not set"
      when: not APIGEE_ENVIRONMENT

    - name: check APIGEE_ORGANIZATION
      fail:
        msg: "APIGEE_ORGANIZATION not set"
      when: not APIGEE_ORGANIZATION

    - name: check APIGEE_ACCESS_TOKEN
      fail:
        msg: "APIGEE_ACCESS_TOKEN not set"
      when: not APIGEE_ACCESS_TOKEN

    - name: check PROXY_DIR
      fail:
        msg: "PROXY_DIR not set"
      when: not PROXY_DIR

    - name: show PING
      debug:
        var: PING

  roles:
    - deploy-apigee-proxy
