- name: "deploy apigee app"
  hosts: 127.0.0.1
  connection: local
  gather_facts: no

  vars:
    SERVICE_NAME: "{{ lookup('env', 'SERVICE_NAME') }}"
    APIGEE_ENVIRONMENT: "{{ lookup('env','APIGEE_ENVIRONMENT') }}"
    APIGEE_ORGANIZATION: "{{ lookup('env', 'APIGEE_ORGANIZATION') }}"
    APIGEE_ACCESS_TOKEN: "{{ lookup('env', 'APIGEE_ACCESS_TOKEN') }}"
    API_PRODUCT: "{{ lookup('env', 'API_PRODUCT') }}"
    CALLBACK_URL: "{{ lookup('env', 'CALLBACK_URL') }}"
    SECRET_LOCATION: "{{ lookup('env', 'SECRET_LOCATION') }}"


  pre_tasks:
    - name: check SERVICE_NAME
      fail:
        msg: "SERVICE_NAME not set"
      when: not SERVICE_NAME

    - name: check APIGEE_ENVIRONMENT
      fail:
        msg: "APIGEE_ENVIRONMENT not set"
      when: not APIGEE_ENVIRONMENT

    - name: check APIGEE_ORGANIZATION
      fail:
        msg: "APIGEE_ORGANIZATION not set"
      when: not APIGEE_ORGANIZATION

    - name: check APIGEE_ACCESS_TOKEN
      fail:
        msg: "APIGEE_ACCESS_TOKEN not set"
      when: not APIGEE_ACCESS_TOKEN
      
    - name: check API_PRODUCT
      fail:
        msg: "API_PRODUCT not set"
      when: not API_PRODUCT

    - name: check CALLBACK_URL
      fail:
        msg: "CALLBACK_URL not set"
      when: not CALLBACK_URL

    - name: check SECRET_LOCATION
      fail:
        msg: "SECRET_LOCATION not set"
      when: not SECRET_LOCATION

  roles:
    - deploy-apigee-app