- name: remove target portal apis
  hosts: 127.0.0.1
  connection: local
  gather_facts: yes

  vars:
    APIGEE_ENVIRONMENT: "{{ lookup('env', 'APIGEE_ENVIRONMENT') }}" 
    APIGEE_ORGANIZATION: "{{ lookup('env', 'APIGEE_ORGANIZATION') }}"
    APIGEE_ACCESS_TOKEN: "{{ lookup('env', 'APIGEE_ACCESS_TOKEN') }}"
    SERVICE_NAME: "{{ lookup('env', 'SERVICE_NAME') }}" 
    SERVICE_NAME_SHORT: "{{ lookup('env', 'SERVICE_NAME_SHORT') }}"  
    regex: "{{ $SERVICE_NAME-$APIGEE_ENVIRONMENT | $SERVICE_NAME_SHORT-$APIGEE_ENVIRONMENT }}"
    has_ecs_backend: "{{ lookup('env', 'has_ecs_backend') }}"

  pre_tasks:
    - name: check APIGEE_ORGANIZATION
      fail:
        msg: "APIGEE_ORGANIZATION not set"
      when: not APIGEE_ORGANIZATION

    - name: check APIGEE_ACCESS_TOKEN
      fail:
        msg: "APIGEE_ACCESS_TOKEN not set"
      when: not APIGEE_ACCESS_TOKEN

  roles:
    - remove-target-portal-apis
    - remove-target-products
    - remove-target-proxies
    - remove-target-specs 

#  include_role:
#    name: remove-target-ecs-backend
#  when: has_ecs_backend 