- name: remove ecr build user
  hosts: 127.0.0.1
  connection: local
  gather_facts: no

  vars:
    service_id:  "{{ lookup('env','service_id') }}"

  pre_tasks:
    - name: check service_id
      fail:
        msg: "service_id not set"
      when: not service_id

  roles:
    - setup-facts
    - remove-ecr-build-user