- name: remove old pr specs
  hosts: 127.0.0.1
  connection: local
  gather_facts: yes

  vars:
    APIGEE_ENVIRONMENT: "internal-dev"
    APIGEE_ORGANIZATION: "{{ lookup('env', 'APIGEE_ORGANIZATION') }}"
    APIGEE_ACCESS_TOKEN: "{{ lookup('env', 'APIGEE_ACCESS_TOKEN') }}"

  pre_tasks:
    - name: check APIGEE_ORGANIZATION
      fail:
        msg: "APIGEE_ORGANIZATION not set"
      when: not APIGEE_ORGANIZATION

    - name: check APIGEE_ACCESS_TOKEN
      fail:
        msg: "APIGEE_ACCESS_TOKEN not set"
      when: not APIGEE_ACCESS_TOKEN

  roles:
    - remove-old-auto-apps
