- name: remove old pr portal apis
  hosts: 127.0.0.1
  connection: local
  gather_facts: yes

  vars:
    APIGEE_ENVIRONMENT: "{{ lookup('env', 'APIGEE_ENVIRONMENT') }}" 
    APIGEE_ORGANIZATION: "{{ lookup('env', 'APIGEE_ORGANIZATION') }}"
    APIGEE_ACCESS_TOKEN: "{{ lookup('env', 'APIGEE_ACCESS_TOKEN') }}"
    SERVICE_NAME: "{{ lookup('env', 'SERVICE_NAME') }}" 
    SERVICE_NAME_SHORT: "{{ lookup('env', 'SERVICE_NAME_SHORT') }}"  

  pre_tasks:
    - name: check APIGEE_ORGANIZATION
      fail:
        msg: "APIGEE_ORGANIZATION not set"
      when: not APIGEE_ORGANIZATION

    - name: check APIGEE_ACCESS_TOKEN
      fail:
        msg: "APIGEE_ACCESS_TOKEN not set"
      when: not APIGEE_ACCESS_TOKEN

  roles:
    - remove-target-proxies
