- name: template proxies
  hosts: 127.0.0.1
  connection: local
  gather_facts: no

  environment:
    AWS_DEFAULT_REGION: eu-west-2

  vars:
    PROXIES_DIR: "{{ lookup('env','PROXIES_DIR') }}"
    SERVICE_BASE_PATH: "{{ lookup('env','SERVICE_BASE_PATH') }}"
    service_id: "{{ lookup('env','service_id') }}"
    APIGEE_ENVIRONMENT: "{{ lookup('env', 'APIGEE_ENVIRONMENT') }}"
    APIGEE_HOSTNAME: "{{ '' if APIGEE_ENVIRONMENT == 'prod' else APIGEE_ENVIRONMENT + '.' }}api.service.nhs.uk"
    APIM_BASENAME: "{{ APIGEE_ENVIRONMENT }}.apis.{{ 'prod' if APIGEE_ENVIRONMENT == 'prod' else 'ptl' }}.api.platform.nhs.uk"
    pr_number: "{{ lookup('env','pr_number') }}"
    APIM_BASE_PATH: "{{ service_id }}{{ '-' + pr_number if pr_number else '' }}"
    APIM_PROXY_HOSTNAME: "{{ service_id }}{{ '-' + pr_number if pr_number else '' }}.{{ APIM_BASENAME }}"
    DEPLOYED_VERSION: "{{ lookup('env', 'DEPLOYED_VERSION') }}"
    RELEASE_RELEASEID: "{{ lookup('env', 'RELEASE_RELEASEID') }}"
    SOURCE_COMMIT_ID: "{{ lookup('env', 'SOURCE_COMMIT_ID') }}"
    HOSTED_TARGET_CONNECTION: |
          <SSLInfo>
            <Enabled>true</Enabled>
          </SSLInfo>
          <LoadBalancer>
            <Server name="hosted-apis"/>
          </LoadBalancer>
          <Path>/{{ service_id }}{{ '-' + pr_number if pr_number else '' }}</Path>
    HOSTED_TARGET_CONNECTION_WITH_PATH_REWRITE: |
          <SSLInfo>
            <Enabled>true</Enabled>
          </SSLInfo>
          <LoadBalancer>
            <Server name="hosted-apis"/>
          </LoadBalancer>
          <Path>/{{ service_id }}{{ '-' + pr_number if pr_number else '' }}/{{fixedpath}}</Path>
    

  roles:
    - template-proxies
