---
build_label: "{{ lookup('env', 'build_label') }}"
images: "{{ docker_containers | json_query('[].name') | unique | sort }}"
service_base_path: "{{ SERVICE_BASE_PATH | regex_replace('^\\/|\\/$', '') }}"
