---

build_label: "{{ lookup('env', 'build_label') }}"
service_base_path: "{{ SERVICE_BASE_PATH | regex_replace('^\\/|\\/$', '') }}"
sub_workspace: "{{ ':' + pr_number if pr_number else '' }}"
namespace: "{{ '-' + pr_number if pr_number else '' }}"
namespaced_name: "{{ service_id }}{{ '-' + pr_number if pr_number else '' }}"
workspace: "api-deployment:{{ account }}:{{ apigee_environment }}:{{ service_id }}{{ sub_workspace }}"
service_cpu: "{{ docker_service_cpu | default(256) }}"
service_memory: "{{ docker_service_memory | default(512) }}"
do_not_terraform: "{{ lookup('env','do_not_terraform') }}"
default_desired_capacity: "{{ 2 if apigee_environment in ('prod', 'ref') else 1  }}"
autoscaling_policy: "{{ docker_service_autoscaling | default({}) | as_ecs_autoscaling }}"