- name: create remote apidoc
  block:
    - name: Increment the retry count
      set_fact:
        create_retry_count: "{{ 0 if create_retry_count is undefined else create_retry_count | int + 1 }}"

    - debug:
        msg: "Retry count: {{ create_retry_count }}"
      when: create_retry_count | int > 0

    - name: send create remote apidoc request
      uri:
        url: "{{ portals_base_uri }}/{{ portal_id }}/apidocs"
        method: POST
        body: "{{ request_body }}"
        body_format: json
        headers:
          Authorization: "Bearer {{ APIGEE_ACCESS_TOKEN }}"
        status_code: 200, 500
      register: create_apidoc

    - name: get all apidocs
      uri:
        url: "{{ portals_base_uri }}/{{ portal_id }}/apidocs"
        method: GET
        headers:
          Authorization: "Bearer {{ APIGEE_ACCESS_TOKEN }}"
        status_code: 200
        return_content: yes
      register: apidocs

    - name: set apidocs
      set_fact:
        apidocs: "{{ apidocs.json.data }}"

    - name: get existing apidocs
      set_fact:
        existing_apidocs: "{{ apidocs | selectattr('edgeAPIProductName', '==', product.name)  | list }}"
    
    - name: assert apidoc has been created!
      assert:
        that:
          - "{{ existing_apidocs | length == 1 }}"
        fail_msg:
          - "reason: Failed updating apidoc" 
          - "status: {{ create_apidoc.status }}"
          - "error: {{ create_apidoc.msg }}"

  rescue:
    - fail:
        msg: Maximum retries of create api docs been reached tasks reached
      when: create_retry_count | int == 4

    - name: Sleep for 15 seconds
      wait_for:
        timeout: 15
      delegate_to: localhost

    - include: create-api-doc.yml