- name: update snapshot
  block:
    - name: Increment the retry count
      set_fact:
        snapshot_retry_count: "{{ 0 if snapshot_retry_count is undefined else snapshot_retry_count | int + 1 }}"

    - debug:
        msg: "Retry count: {{ snapshot_retry_count }}"
      when: snapshot_retry_count | int > 0

    - name: update local apidoc
      set_fact:
        apidoc: "{{ create_apidoc.json.data | default(updated_apidoc.json.data) }}"

    - name: update remote snapshot
      uri:
        url: "{{ portals_base_uri }}/{{ portal_id }}/apidocs/{{ apidoc.id }}/snapshot"
        method: "{{ (SPEC_FILE) | ternary('PUT', 'DELETE') }}"
        headers:
          Authorization: "Bearer {{ APIGEE_ACCESS_TOKEN }}"
        status_code: 200, 500
      register: snapshot

    - name: get updated apidoc, on snapshot update
      uri:
        url: "{{ portals_base_uri }}/{{ portal_id }}/apidocs/{{ apidoc.id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ APIGEE_ACCESS_TOKEN }}"
        status_code: 200
        return_content: yes
      register: updated_snapshot

    - name: get epoch date
      command: date -u +%s
      register: epoch_date

    - name: assert snapshot has been updated
      assert:
        that:
          - "{{ (epoch_date.stdout_lines[0] | int) - (updated_snapshot.json.data.snapshotModified / 1000) < 30 }}"
        fail_msg:
          - "reason: Failed updating snapshot" 
          - "status: {{ snapshot.status }}"
          - "error: {{ snapshot.msg }}"

  rescue:
    - fail:
        msg: Maximum retries of create api docs been reached tasks reached
      when: snapshot_retry_count | int == 4

    - name: Sleep for 15 seconds
      wait_for:
        timeout: 15
      delegate_to: localhost

    - include: update-snapshot.yml
