- name: update snapshot
  block:
    - name: Increment the retry count
      set_fact:
        retry_count: "{{ 0 if retry_count is undefined else retry_count | int + 1 }}"

    - debug:
        msg: "Retry count: {{ retry_count }}"
      when: retry_count | int > 0

    - name: Update remote snapshot
      uri:
        url: "{{ portals_base_uri }}/{{ portal_id }}/apidocs/{{ apidoc.id }}/snapshot"
        method: "{{ (SPEC_FILE) | ternary('PUT', 'DELETE') }}"
        headers:
          Authorization: "Bearer {{ APIGEE_ACCESS_TOKEN }}"
        status_code: 200, 500
      register: snapshot

    - name: get all apidocs, on snapshot update
      uri:
        url: "{{ portals_base_uri }}/{{ portal_id }}/apidocs"
        method: GET
        headers:
          Authorization: "Bearer {{ APIGEE_ACCESS_TOKEN }}"
        status_code: 200
        return_content: yes
      register: apidocs

    - name: set apidocs, on snapshot update
      set_fact:
        apidocs: "{{ apidocs.json.data }}"

    - name: get existing apidocs, on snapshot update
      set_fact:
        existing_apidocs: "{{ apidocs | selectattr('edgeAPIProductName', '==', product.name) | list }}"

    - name: assert snapshot has been updated
      assert:
        that:
          - "{{ (existing_apidocs[0].snapshotModified / 1000) - (ansible_date_time.epoch | int) < 30 }}"

  rescue:
    - fail:
        msg: Maximum retries of create api docs been reached tasks reached
      when: retry_count | int == 4

    - name: Sleep for 15 seconds
      wait_for:
        timeout: 15
      delegate_to: localhost

    - include: update-snapshot.yml