- name: update remote apidoc
  block:
    - name: Increment the retry count
      set_fact:
        update_retry_count: "{{ 0 if update_retry_count is undefined else update_retry_count | int + 1 }}"

    - debug:
        msg: "Retry count: {{ update_retry_count }}"
      when: update_retry_count | int > 0

    - name: send update remote apidoc
      uri:
        url: "{{ portals_base_uri }}/{{ portal_id }}/apidocs/{{ apidoc.id }}"
        method: PUT
        body: "{{ request_body }}"
        body_format: json
        headers:
          Authorization: "Bearer {{ APIGEE_ACCESS_TOKEN }}"
        status_code: 200, 500

    - name: get updated apidoc
      uri:
        url: "{{ portals_base_uri }}/{{ portal_id }}/apidocs/{{ apidoc.id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ APIGEE_ACCESS_TOKEN }}"
        status_code: 200
        return_content: yes
      register: updated_apidoc

    - name: get epoch date
      command: date -u +%s
      register: epoch_date

    - name: assert apidoc has been updated
      assert:
        that:
          - "{{ (epoch_date.stdout_lines[0] | int) - (updated_apidoc.json.data.modified / 1000) < 30 }}"
        fail_msg:
          - "reason: Failed updating apidoc" 
          - "status: {{ update_apidoc.status }}"
          - "error: {{ update_apidoc.msg }}"

  rescue:
    - fail:
        msg: Maximum retries of create api docs been reached tasks reached
      when: update_retry_count | int == 4

    - name: Sleep for 15 seconds
      wait_for:
        timeout: 15
      delegate_to: localhost

    - include: update-api-doc.yml
