

- debug: msg="{{ product_slug }} - {{ item.appName}} - {{ dev_id_to_email[item.developerId] }} - {{ apigee_teams_to_members[dev_id_to_email[item.developerId]] | default(dev_id_to_email[item.developerId]) }}"
  loop: "{{ product_app_map.get(product_slug, []) }}"
  loop_control:
    label: "{{ product_slug }} - {{ item.appName }} - {{ item.appId }}"

