APIGEE_ORGANIZATION: "{{ lookup('env', 'APIGEE_ORGANIZATION')}}"
APIGEE_ENVIRONMENT: "{{ lookup('env', 'APIGEE_ENVIRONMENT')}}"
APIGEE_ACCESS_TOKEN: "{{ lookup('env', 'APIGEE_ACCESS_TOKEN')}}"
APP_ID: "{{ lookup('env', 'APP_ID')}}"
