name: Test deployments

on: [pull_request]

jobs:
  test_deployments:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Scripts
      uses: actions/checkout@v2

    - name: Get azure devops token
      run: |
        az login -u ${{ secrets.DEVOPS_USEREMAIL }} -p ${{ secrets.DEVOPS_PASSWORD }} --allow-no-subscriptions
        echo 'AZURE_TOKEN=`az account get-access-token | jq -r ".accessToken"`' >> $GITHUB_ENV

    - name: Run Script
      run: |
        export BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
        export NOTIFY_COMMIT_SHA=$(git rev-parse HEAD)
        export UTILS_PR_NUMBER="${{ github.event.pull_request.number }}"
        export AZURE_TOKEN="$AZURE_TOKEN"
        echo BRANCH_NAME=${BRANCH_NAME}
        echo NOTIFY_COMMIT_SHA=${NOTIFY_COMMIT_SHA}
        echo UTILS_PR_NUMBER=${UTILS_PR_NUMBER}
        echo AZURE_TOKEN="${AZURE_TOKEN}"
        python3 scripts/test_deployments.py
