name: Test deployments

on: 
  push:
    tags:
      - v*
  pull_request:
    branches:
      - APM-*

jobs:
  test_deployments:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Scripts
      uses: actions/checkout@v2

    - name: Run Scripts
      env:
        AZURE_TOKEN: "${{ secrets.AZURE_TOKEN }}"
      run: |
        export BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
        export NOTIFY_COMMIT_SHA=$(git rev-parse HEAD)
        export UTILS_PR_NUMBER="${{ github.event.pull_request.number }}"
        echo BRANCH_NAME=${BRANCH_NAME}
        echo NOTIFY_COMMIT_SHA=${NOTIFY_COMMIT_SHA}
        echo UTILS_PR_NUMBER=${UTILS_PR_NUMBER}
        python3 scripts/test_deployments.py
