name: Build

on: [pull_request]

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install poetry
        run: pip install poetry

      - name: Cache poetry packages
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.venv
          key: ${{ runner.os }}-utils-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Unit test ansible collection
        working-directory: ansible/collections/ansible_collections/nhsd/apigee
        run: poetry run ansible-test units --python=3.8

      - name: Integration test ansible collection
        working-directory: ansible/collections/ansible_collections/nhsd/apigee
        run: poetry run ansible-test integration --python=3.8
