
- name: "get developers"
  uri:
    url: "{{ developers_uri }}?expand=true"
    headers:
      Authorization: "Bearer {{ APIGEE_ACCESS_TOKEN }}"
    return_content: yes
  register: get_developers

- name: "map developers"
  set_fact:
    dev_id_to_email: "{{ get_developers.json.developer | dict_list_to_map('developerId', 'email') }}"

- name: "get apps"
  uri:
    url: "{{ apps_uri }}?expand=true"
    headers:
      Authorization: "Bearer {{ APIGEE_ACCESS_TOKEN }}"
    return_content: yes
    timeout: 90
  register: get_apps

- name: create product map
  set_fact:
    product_app_map: "{{ get_apps.json.app | apigee_apps_to_product_map(product_filter=service_name_env)}}"

- name: get products
  uri:
    url: "{{ products_uri }}"
    headers:
      Authorization: "Bearer {{ APIGEE_ACCESS_TOKEN }}"
    return_content: yes
  register: products

- name: filter products
  set_fact:
    target_products: "{{  products.json | select('match', service_name_env) }}"

- debug:
    msg: "{{ target_products }}"

- name: remove target products
  include_tasks: remove-product.yml
  loop: "{{ target_products }}"
  loop_control:
    loop_var: "product_slug"
